# / .continue/config.yaml
models:
  - id: gpt-4o-mini
    provider: openia
    baseUrl: https://models.interface.ai.azure.com
    apiKey : ${TOK.MRC.01}
    tabAutocompleteModel: gpt-4o-mini
    defaultModel: gpt-4o-mini
    
